### ISSUE TITLE
SSL error in clamd server

### ISSUE THREAD

**Issue by rnkhouse** [solita/clamav-rest#25]
I am getting an SSL error in clamd server while updating the database.

    Thu Feb 20 19:22:48 2020 -> daily database available for update (local version: 25728, remote version: 25729)
    Thu Feb 20 19:22:51 2020 -> ^Download failed (60) Thu Feb 20 19:22:51 2020 -> ^ Message: SSL peer certificate or SSH remote key was not OK
    Thu Feb 20 19:22:51 2020 -> ^getpatch: Can't download daily-25729.cdiff from https://database.clamav.net/daily-25729.cdiff
    Thu Feb 20 19:22:56 2020 -> ^Download failed (60) Thu Feb 20 19:22:56 2020 -> ^ Message: SSL peer certificate or SSH remote key was not OK
    Thu Feb 20 19:22:56 2020 -> ^getpatch: Can't download daily-25729.cdiff from https://database.clamav.net/daily-25729.cdiff
    Thu Feb 20 19:22:56 2020 -> ^Download failed (60) Thu Feb 20 19:22:56 2020 -> ^ Message: SSL peer certificate or SSH remote key was not OK
    Thu Feb 20 19:22:56 2020 -> ^getpatch: Can't download daily-25729.cdiff from https://database.clamav.net/daily-25729.cdiff
    Thu Feb 20 19:22:56 2020 -> ^Download failed (60) Thu Feb 20 19:22:56 2020 -> ^ Message: SSL peer certificate or SSH remote key was not OK
    Thu Feb 20 19:22:56 2020 -> ^getpatch: Can't download daily-25729.cdiff from https://database.clamav.net/daily-25729.cdiff
    Thu Feb 20 19:22:56 2020 -> !Download failed (60) Thu Feb 20 19:22:56 2020 -> ! Message: SSL peer certificate or SSH remote key was not OK
    Thu Feb 20 19:22:56 2020 -> !getpatch: Can't download daily-25729.cdiff from https://database.clamav.net/daily-25729.cdiff
    Thu Feb 20 19:22:56 2020 -> ^Incremental update failed, trying to download daily.cvd
    Thu Feb 20 19:22:56 2020 -> !Download failed (60) Thu Feb 20 19:22:56 2020 -> ! Message: SSL peer certificate or SSH remote key was not OK
    Thu Feb 20 19:22:56 2020 -> !getcvd: Can't download daily.cvd from https://database.clamav.net/daily.cvd
    Thu Feb 20 19:22:56 2020 -> Giving up on https://database.clamav.net...
    Thu Feb 20 19:22:56 2020 -> !Update failed for database: daily
    Thu Feb 20 19:22:56 2020 -> ^fc_update_databases: fc_update_database failed: Connection failed (5)
    Thu Feb 20 19:22:56 2020 -> !Database update process failed: Connection failed (5)
    Thu Feb 20 19:22:56 2020 -> !Update failed.

**Comment by alansbb** [comment]
Same here, hopefully someone already solve the issue?

**Comment by sean-quinn** [comment]
@rnkhouse @alansbb did you guys try updating your certificate-store and restarting clamav? i updated the following in my ubuntu docker image running clamd/freshclam and i no longer see this error.

```
apt-get update && apt-get install ca-certificates
update-ca-certificates
```

**Comment by alansbb** [comment]
@sean-quinn  Really appreciated! working!

**Comment by rnkhouse** [comment]
It worked for me as well. Thanks.

**Comment by Waywardnl** [comment]
I had this problem under windows, i installed version 1.04, then tried freshclam.exe, got the error. Deinstalled 1.04 installed 1.03, then installed 1.04 together with 1.03. Then i got an error. Then deinstalled all ClamAV instances, then installed 1.03. Problem solved.
