### ISSUE TITLE
Spring Boot could do with an update

### ISSUE THREAD

**Issue by ptribble** [solita/clamav-rest#5]
Can the Spring Boot component be updated from 1.1.6 to 1.4.0?

Other than being newer, this would allow ssl to be enabled, which is a requirement for some users.

(I've tested simply updating the version in pom.xml and it works fine.)

**Comment by lokori** [comment]
Ok, here it is. I upgraded the clamav-rest version from 1.0.0 to 1.0.1 to reflect this.
